version: '3.8'

services:
  ambev.developerevaluation.webapi:
    container_name: ambev_developer_evaluation_webapi
    build:
      context: .
      dockerfile: src/Ambev.DeveloperEvaluation.WebApi/Dockerfile
    ports:
      - "8080:8080"

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - ambev_dev_net
    restart: unless-stopped
    depends_on:
      - ambev.developerevaluation.database
      - rabbitmq

  ambev.developerevaluation.database:
    container_name: ambev_developer_evaluation_database
    image: postgres:13
    environment:
      POSTGRES_DB: developer_evaluation
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: ev@luAt10n
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - ambev_dev_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq-host
    ports:
      - "5672:5672" 
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: developer
      RABBITMQ_DEFAULT_PASS: ev@luAt10n
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - ambev_dev_net

  # ambev.developerevaluation.nosql:
  #   container_name: ambev_developer_evaluation_nosql 
  #   image: mongo:8.0    
  #   environment:
  #       MONGO_INITDB_ROOT_USERNAME: developer
  #       MONGO_INITDB_ROOT_PASSWORD: ev@luAt10n
  #   ports:
  #     - "27017"

  # ambev.developerevaluation.cache:
  #   container_name: ambev_developer_evaluation_cache 
  #   image: redis:7.4.1-alpine     
  #   command: redis-server --requirepass ev@luAt10n
  #   environment:
  #      MONGO_INITDB_ROOT_USERNAME: developer
  #      MONGO_INITDB_ROOT_PASSWORD: ev@luAt10n
  #   ports:
  #      - "6379"

networks:
  ambev_dev_net:

volumes:
  rabbitmq_data:
  postgres_data: